file_suffix_dict = {
    '.sh': 'bash',
    '.c': 'c',
    '.cs': 'c_sharp',
    '.cpp': 'cpp',
    '.css': 'css',
    '.dockerfile': 'dockerfile',
    '.dot': 'dot',
    '.el': 'elisp',
    '.ex': 'elixir',
    '.elm': 'elm',
    '.erl': 'erlang',
    '.f90': 'fortran',
    '.go': 'go',
    '.mod': 'gomod',
    '.hh': 'hack',
    '.hs': 'haskell',
    '.hcl': 'hcl',
    '.html': 'html',
    '.java': 'java',
    '.js': 'javascript',
    '.jsdoc': 'jsdoc',
    '.json': 'json',
    '.jl': 'julia',
    '.kt': 'kotlin',
    '.lua': 'lua',
    '.mk': 'make',
    '.md': 'markdown',
    '.m': 'objc',
    '.ml': 'ocaml',
    '.pl': 'perl',
    '.php': 'php',
    '.py': 'python',
    '.ql': 'ql',
    '.r': 'r',
    '.regex': 'regex',
    '.rst': 'rst',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.scala': 'scala',
    '.sql': 'sql',
    '.sqlite': 'sqlite',
    '.toml': 'toml',
    '.tsq': 'tsq',
    '.ts': 'typescript',
    '.yaml': 'yaml'
}

lang = file_suffix_dict.get(".yuan")
print(lang)
